DROP TABLE IF EXISTS USERS;
CREATE TABLE USERS (
	email VARCHAR(50) NOT NULL,
	password VARCHAR(20) NOT NULL,
	passwordConfirm VARCHAR(20)	NOT NULL,
	
	PRIMARY KEY (email)
);

DROP TABLE IF EXISTS TUMBLER;
CREATE TABLE TUMBLER (
	id VARCHAR(20) NOT NULL,
	water VARCHAR(10) NOT NULL,
	
	PRIMARY KEY (id)
);

INSERT INTO USERS VALUES('asto@as.com', 'test', 'test');
INSERT INTO TUMBLER VALUES('test', '0');